language: python

python:
  - "3.5"

sudo: false
cache: pip

addons:
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml # because pip installation is slow

env:
  global:
  - VERSION="12.0" TESTS="0" LINT_CHECK="1" TRANSIFEX="0"

  matrix:
  - LINT_CHECK="1"

git:
  submodules: false

install:
  - git clone --depth=1 https://github.com/brain-tec/maintainer-quality-tools.git -b BT ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly

script:
  - travis_run_tests

after_success:
- travis_after_tests_success